// Easy_Enum.h: Easy library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __EASY_ENUM__H_
#define __EASY_ENUM__H_

// In-ETrace-macro flag
#define E_ETRACE_USED 0x4

// Image file types
enum IMAGE_FILE_TYPES
{ 
  E_FILE_FORMAT_BILEVEL_TIFF,
  E_FILE_FORMAT_GRAY_LEVEL_TIFF,
  E_FILE_FORMAT_COLOR_TIFF,
  E_FILE_FORMAT_PACKED_BILEVEL_TIFF,
  E_FILE_FORMAT_PACKED_GRAY_LEVEL_TIFF,
  E_FILE_FORMAT_PACKED_COLOR_TIFF, // UNUSED
  E_FILE_FORMAT_BILEVEL_BMP,
  E_FILE_FORMAT_GRAY_LEVEL_BMP,
  E_FILE_FORMAT_COLOR_BMP,
  E_FILE_FORMAT_BILEVEL_JPEG, // UNUSED
  E_FILE_FORMAT_GRAY_LEVEL_JPEG,
  E_FILE_FORMAT_COLOR_JPEG,

  E_FILE_FORMAT_AUTO,

  // Generic types
  E_FILE_FORMAT_TIFF = E_FILE_FORMAT_GRAY_LEVEL_TIFF,
  E_FILE_FORMAT_BMP = E_FILE_FORMAT_GRAY_LEVEL_BMP,
  E_FILE_FORMAT_JPEG = E_FILE_FORMAT_GRAY_LEVEL_JPEG,

  E_FILE_FORMAT_UNKNOWN  = 0xFFFFFFFF
};

// Predefined image types
enum E_IMAGE_TYPES
{
  E_BW1,
  E_BW8,
  E_BW16,
  E_BW32,
  E_C15,
  E_C16,
  E_C24,
  E_C24A,
  E_GRADIENT32,
  E_SUBPIXEL64,
  E_COMPLEX64,
  E_RAW32,
  E_RAW96,
  E_YUY2,
  E_FLOAT32,
  E_FLOAT64,

  E_UNKNOWN  = 0xFFFFFFFF
};

// Handle names
enum E_HANDLES
{
  E_HANDLE_NONE,
  E_HANDLE_INSIDE,
  E_HANDLE_NORTH,
  E_HANDLE_EAST,
  E_HANDLE_SOUTH,
  E_HANDLE_WEST,
  E_HANDLE_NORTH_WEST,
  E_HANDLE_SOUTH_WEST,
  E_HANDLE_NORTH_EAST,
  E_HANDLE_SOUTH_EAST,
  E_HANDLE_UNKNOWN  = 0xFFFFFFFF
};

// Frame drawing position
enum E_FRAME_POSITION
{
  E_FRAME_ON,
  E_FRAME_INSIDE,
  E_FRAME_OUTSIDE,
  E_FRAME_UNKNOWN  = 0xFFFFFFFF
};

// Colorimetric systems
enum E_COLOR_SYSTEM
{ 
  E_COLOR_SYSTEM_NONE,

  // Achromatic
  E_COLOR_SYSTEM_BILEVEL,
  E_COLOR_SYSTEM_GRAY_LEVEL,

  // Raw color components
  E_COLOR_SYSTEM_XYZ,
  E_COLOR_SYSTEM_RGB,
  //E_COLOR_SYSTEM_CMY, // UNUSED
  //E_COLOR_SYSTEM_CMYK, // UNUSED

  // Luminance/chrominance
  E_COLOR_SYSTEM_LAB,
  E_COLOR_SYSTEM_LUV,
  E_COLOR_SYSTEM_YUV,
  E_COLOR_SYSTEM_YIQ,

  // Luminance/hue/saturation
  E_COLOR_SYSTEM_LCH,
  E_COLOR_SYSTEM_ISH,
  E_COLOR_SYSTEM_LSH,
  E_COLOR_SYSTEM_VSH,
  E_COLOR_SYSTEM_YSH,

  // Labelized
  E_COLOR_SYSTEM_LABELIZED,

  // Gradient
  E_COLOR_SYSTEM_GRADIENT,

  E_COLOR_SYSTEM_UNKNOWN  = 0xFFFFFFFF
};


////////////////////////////////////////////////////////////////////////////////////////////////////
// Error codes
//
enum E_ERRORS
{
  E_OK = 0,

  E_ERROR_FIRST_INFO_CODE = 100,
  E_ERROR_FIRST_ERROR_CODE = 1000,

  // General
  E_ERROR_CANNOT_TRACE_ERRORS = 32765,
  E_ERROR_FEATURE_NOT_YET_IMPLEMENTED = 32766,
  E_ERROR_INTERNAL_ERROR = 32767,
  E_ERROR_NOT_A_VALID_DESCRIPTOR = 1000,
  E_ERROR_INITIALIZATION_ERROR = 1002,
  E_ERROR_INVALID_OPERATION = 1003,
  E_ERROR_INVALID_BITS_PER_PIXEL = 1004,
  E_ERROR_INVALID_DATA_TYPE = 1005,
  E_ERROR_INVALID_DATA_SIZE = 1006,
  E_ERROR_CONSTANT_VALUE_TOO_LARGE = 1008,
  E_ERROR_INVALID_MODE = 1009,
  E_ERROR_END_SMALLER_THAN_START = 1010,
  E_ERROR_PARAMETERS_OUT_OF_RANGE = 1007,
  E_ERROR_PARAMETER_1_OUT_OF_RANGE = 1011,
  E_ERROR_PARAMETER_2_OUT_OF_RANGE = 1012,
  E_ERROR_PARAMETER_3_OUT_OF_RANGE = 1013,
  E_ERROR_PARAMETER_4_OUT_OF_RANGE = 1014,
  E_ERROR_PARAMETER_5_OUT_OF_RANGE = 1015,
  E_ERROR_PARAMETER_6_OUT_OF_RANGE = 1016,
  E_ERROR_PARAMETER_7_OUT_OF_RANGE = 1017,
  E_ERROR_PARAMETER_8_OUT_OF_RANGE = 1018,
  E_ERROR_PARAMETER_9_OUT_OF_RANGE = 1019,
  E_ERROR_PARAMETER_10_OUT_OF_RANGE = 1020,
  E_ERROR_WINDOWS_ERROR = 1021,
  E_ERROR_INVALID_PLANES_PER_PIXEL = 1022,
  E_ERROR_BW1_IMAGE_EXPECTED = 1023,
  E_ERROR_BW8_IMAGE_EXPECTED = 1024,
  E_ERROR_BW16_IMAGE_EXPECTED = 1025,
  E_ERROR_BW32_IMAGE_EXPECTED = 1026,
  E_ERROR_C15_IMAGE_EXPECTED = 1027,
  E_ERROR_C16_IMAGE_EXPECTED = 1028,
  E_ERROR_C24_IMAGE_EXPECTED = 1029,
  E_ERROR_GRADIENT32_IMAGE_EXPECTED = 1030,
  E_ERROR_TEMPLATE_CALL_NEEDS_SPECIALIZATION = 1031,
  E_ERROR_CANNOT_CREATE_MUTEX = 1032,
  E_ERROR_CANNOT_LOCK_MUTEX = 1033,
  E_ERROR_CANNOT_UNLOCK_MUTEX = 1034,
  E_ERROR_CANNOT_DELETE_MUTEX = 1035,
  E_ERROR_TIMEOUT_REACHED = 1036,
  E_ERROR_NOT_SUPPORTED_UNDER_LINUX = 1037,
  
  // Numerical processing
  E_ERROR_SINGULAR_MATRIX = 1050,
  E_ERROR_DIVISION_BY_ZERO = 1051,

  // properties
  E_ERROR_READONLY_PROPERTY = 1052,
  E_ERROR_UNDEFINED_PROPERTY = 1053,

  // File access
  E_ERROR_FILE_ACCESS_PROBLEMS = 1100,
  E_ERROR_FILE_NOT_FOUND = 1101,
  E_ERROR_FILE_COULD_NOT_BE_OPENED = 1102,
  E_ERROR_FILE_ERROR_WHILE_READING = 1103,
  E_ERROR_FILE_ERROR_WHILE_WRITING = 1104,
  E_ERROR_BAD_FILE_FORMAT = 1105,
  E_ERROR_FILE_COULD_NOT_BE_CLOSED = 1106,
  E_ERROR_OBSOLETE_FILE_FORMAT = 1107,
  E_ERROR_UNSUPPORTED_FILE_FORMAT_VERSION = 1108,
  E_ERROR_MISSING_OR_UNSUPPORTED_FILE_EXTENSION = 1109,
  E_ERROR_FILE_IS_READ_ONLY = 1110,
  E_ERROR_UNSUPPORTED_OBJECT_TYPE_IN_ARCHIVE = 1111,
  E_ERROR_UNKNOWN_ARCHIVE_ERROR = 1112,
  E_ERROR_SERIALIZER_SHOULD_BE_IN_READ_MODE = 1113,
  E_ERROR_SERIALIZER_SHOULD_BE_IN_WRITE_MODE = 1114,
  E_ERROR_FILE_EXISTS = 1115,
  E_ERROR_SERIALIZER_NOT_OPEN = 1116,

  // AVI
  E_ERROR_MISSING_OR_INVALID_AVI_STREAM = 1150,
  E_ERROR_UNSUPPORTED_AVI_STREAM_TYPE = 1151,
  E_ERROR_AVI_COMPRESSOR_NOT_FOUND = 1152,
  E_ERROR_AVI_COMPRESSOR_DOES_NOT_SUPPORT_THIS_IMAGE_FORMAT = 1153,

  // Load/save images
  E_ERROR_UNABLE_TO_LOAD_INTO_AN_ROI = 1200,
  E_ERROR_UNABLE_TO_SAVE_FROM_AN_ROI = 1201,
  E_ERROR_UNSUPPORTED_TIFF_FORMAT = 1202,

  E_ERROR_UNSUPPORTED_BMP_FORMAT = 1203,
  E_ERROR_DISK_IMAGE_TOO_WIDE_FOR_BLOCK = 1204,
  E_ERROR_TOO_MANY_BITS_PER_PIXEL = 1205,
  E_ERROR_UNSUPPORTED_VISILOG_FORMAT = 1206,
  E_ERROR_UNSUPPORTED_JPEG_FORMAT = 1207,
  E_ERROR_BILEVEL_IMAGE_EXPECTED = 1208,
  E_ERROR_GRAY_LEVEL_IMAGE_EXPECTED = 1209,
  E_ERROR_COLOR_IMAGE_EXPECTED = 1210,
  E_ERROR_BILEVEL_FORMAT_EXPECTED = 1212,
  E_ERROR_GRAY_LEVEL_FORMAT_EXPECTED = 1213,
  E_ERROR_COLOR_FORMAT_EXPECTED = 1214,
  E_ERROR_CANNOT_READ_JPEG_FILE = 1215,
  E_ERROR_CANNOT_WRITE_JPEG_FILE = 1216,

  // Memory allocation
  E_ERROR_UNABLE_TO_ALLOCATE_TEMPORARY_MEMORY = 1301,
  E_ERROR_INSUFFICIENT_ALLOC_MEM = 1302,
  E_ERROR_UNABLE_TO_ALLOCATE_MEMORY = 1303,
  E_ERROR_UNABLE_TO_REALLOC_MEMORY = 1304,

  // Xlib
  E_ERROR_XSHMSEGINFO = 1350,
  E_ERROR_XSHMATTACH = 1351,
  E_ERROR_XSHMXIMAGE = 1352,
  E_ERROR_XIMAGE = 1353,

  // Images
  E_ERROR_UNABLE_TO_ACCESS_IMAGE_MEMORY = 1400,
  E_ERROR_ROI_TOO_LARGE = 1401,
  E_ERROR_NOT_A_VALID_IMAGE = 1402,
  E_ERROR_IMAGES_NOT_SAME_SIZE = 1403,
  E_ERROR_IMAGES_NOT_SAME_BITS_PER_PIXEL = 1404,
  E_ERROR_SOURCE_IMAGE_TOO_SMALL = 1405,
  E_ERROR_UNABLE_TO_MODIFY_ROI = 1406,
  E_ERROR_UNABLE_TO_MODIFY_PARENT_IMAGE_ORG = 1407,
  E_ERROR_UNABLE_TO_MODIFY_PARENT_IMAGE_SIZE = 1408,
  E_ERROR_PIXELS_MUST_HAVE_FINITE_SIZE = 1409,
  E_ERROR_PIXELS_MUST_HAVE_POSITIVE_SIZE = 1410,
  E_ERROR_CONSTANT_IS_NULL = 1411,
  E_ERROR_PIXEL_NULL_ENCOUNTERED = 1412,
  E_ERROR_IMAGES_MAY_NOT_OVERLAP = 1413,
  E_ERROR_ROI_OUT_OF_PARENT_LIMITS = 1414,
  E_ERROR_ROI_ALREADY_HAS_A_PARENT = 1415,
  E_ERROR_ROI_HAS_NO_PARENT_IMAGE = 1416,
  E_ERROR_CANNOT_APPLY_TO_AN_IMAGE = 1417,
  E_ERROR_UNSUPPORTED_IMAGE_TYPE = 1418,
  E_ERROR_INVALID_IMAGE_TYPE = 1419,
  E_ERROR_UNSUPPORTED_XSERVER_DEPTH = 1420,
  E_ERROR_INCONSISTENT_ROI_HIERARCHY = 1421,
  E_ERROR_SOURCE_IMAGE_TOO_BIG = 1422,
  E_ERROR_BW1_ROI_NOT_ALIGNED =1423,

  // Image sequences
  E_ERROR_UNSUPPORTED_IMAGE_SEQUENCE_FORMAT = 1450,
  E_ERROR_UNSUPPORTED_IMAGE_SEQUENCE_FILE_FORMAT = 1451,
  E_INFO_END_OF_IMAGE_SEQUENCE = 104,
  E_INFO_USER_DIALOG_FAILED = 105,

  // Contour
  E_ERROR_PIXEL_OUTSIDE_PERIMETER = 1500,
  E_ERROR_PIXEL_INSIDE_PERIMETER = 1501,
  E_ERROR_ISOLATED_PIXEL = 1502,
  E_INFO_IMAGE_LIMITS_REACHED = 106,
  E_ERROR_MAX_PIXEL_IN_CONTOUR_REACHED = 1504,
  E_ERROR_NOT_A_VALID_CONTOUR = 1505,

  // Vectors
  E_ERROR_UNABLE_TO_ACCESS_VECTOR_MEMORY = 1601,
  E_ERROR_NOT_A_VALID_VECTOR_DESCRIPTOR = 1602,
  E_ERROR_VECTOR_TYPE_IS_NOT_HIST = 1603,
  E_ERROR_NOT_ENOUGH_GROUPS_IN_VECTOR = 1604,
  E_ERROR_INVALID_VECTOR_DATA_SIZE = 1605,

  E_ERROR_INVALID_VECTOR_DATA_TYPE = 1606,
  E_ERROR_INVALID_VECTOR_TYPE = 1607,
  E_ERROR_RESULT_TOO_BIG_TO_FIT_IN_VECTOR = 1608,
  E_ERROR_GROUP_OUT_OF_RANGE = 1609,
  E_ERROR_INVALID_VECTOR_USE = 1610,
  E_ERROR_INVALID_VECTOR_GROUP_LENGTH = 1611,
  E_ERROR_INVALID_VECTOR_NUMBER_OF_GROUPS = 1612,
  E_ERROR_INVALID_NUMBER_OF_VECTOR_ELEMENTS = 1613,
  E_ERROR_UNSUPPORTED_VECTOR_TYPE = 1614,
  E_ERROR_VECTORS_NOT_SAME_SIZE = 1615,
  E_ERROR_ITEM_NOT_IN_VECTOR = 1616,

  // Kernels
  E_ERROR_UNABLE_TO_ACCESS_KERNEL_MEMORY = 1700,
  E_ERROR_NOT_A_VALID_KERNEL_DESCRIPTOR = 1701,
  E_ERROR_INVALID_KERNEL = 1702,
  E_ERROR_KERNEL_INVALID_SIZE = 1703,
  E_ERROR_KERNEL_NOT_ALLOCATED = 1704,

  // List
  E_ERROR_LIST_ALREADY_INITIALIZED = 1800,
  E_ERROR_LIST_NOT_INITIALIZED = 1801,
  E_ERROR_BAD_LIST_POSITION = 1802,
  E_ERROR_LIST_IS_EMPTY = 1803,
  E_ERROR_TOP_OF_LIST = 1804,
  E_ERROR_BOT_OF_LIST = 1805,
  E_ERROR_LIST_ERROR = 1806,

  // Libraries authorization
  E_ERROR_LICENSE_MISSING = 1900,
  E_ERROR_LICENSE_KEY_MISSING = 1901,
  E_ERROR_LICENSE_WRONG_KEY_TYPE = 1902,
  E_ERROR_LICENSE_EXPIRED = 1903,

  E_ERROR_EASY_ACCESS_LICENSE_MISSING = 1904,
  E_ERROR_EASY_IMAGE_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 1,
  E_ERROR_EASY_OBJECT_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 2,
  E_ERROR_EASY_MEASURE_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 3,
  E_ERROR_EASY_OCR_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 4,
  E_ERROR_EASY_HCR_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 5,
  E_ERROR_EASY_MATCH_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 6,
  E_ERROR_EASY_GRANULA_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 7,
  E_ERROR_EASY_OPV_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 8,
  E_ERROR_EASY_COLOR_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 9,
  E_ERROR_EASY_OCV_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 10,
  E_ERROR_EASY_MATRIX_CODE_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 11,
  E_ERROR_EASY_INSPECT_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 12,
  E_ERROR_EASY_BGA_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 13,
  E_ERROR_EASY_FIND_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 14,
  E_ERROR_EASY_GAUGE_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 15,
  E_ERROR_EASY_BAR_CODE_LICENSE_MISSING = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 16,
  E_ERROR_FEATURE_NOT_AVAILABLE = E_ERROR_EASY_ACCESS_LICENSE_MISSING + 17,
  E_ERROR_EURECARD_MISSING = 1950,
  E_ERROR_EURECARD_DOMINO_MISSING = 1951,
  E_ERROR_EURECARD_PICOLO_MISSING = 1952,
  E_ERROR_EURECARD_MULTI_MISSING = 1953,
  E_ERROR_EURECARD_SIRCAM_MISSING = 1954,
  E_ERROR_NO_PLACE_TO_WRITE_OEM_KEY_IN = 1955,
  E_ERROR_NO_SENTINEL_DONGLE_TO_WRITE_OEM_KEY_IN = 1956,
  E_ERROR_NO_EURECARD_TO_WRITE_OEM_KEY_IN = 1957,
  E_ERROR_CANNOT_WRITE_KEY_IN_SENTINEL_DONGLE  = 1958,
  E_ERROR_CANNOT_WRITE_KEY_IN_EURECARD = 1959,
  E_ERROR_CANNOT_WRITE_OEMKEY = 1960,

  // Libraries authorization file
  E_ERROR_COULD_NOT_READ_THE_LICENSE_FILE = 2000,
  E_ERROR_COULD_NOT_GRANT_THE_LICENSES = 2001,
  E_ERROR_LICENSE_PATH_NOT_DEFINED = 2002,
  E_ERROR_BAD_CONTENTS = 2003,
  E_ERROR_BAD_CONTENTS_COULD_NOT_BE_LOGGED = 2004,
  E_ERROR_WRONG_CHECKSUM = 2005,
  E_ERROR_BAD_SERIAL_NO = 2006,
  E_ERROR_BAD_PART_NAME = 2007,
  E_ERROR_BAD_PART_NO = 2008,
  E_ERROR_PART_MISMATCH = 2009,
  E_ERROR_BAD_EXPIRES = 2010,
  E_ERROR_BAD_ACCESS_KEY = 2011,
  E_ERROR_BAD_CHECKSUM = 2012,
  E_ERROR_BAD_DATE = 2013,
  E_ERROR_BAD_HOUR = 2014,
  E_ERROR_LICENSE_FILE_NOT_FOUND = 2015,

  // General licence holders
  E_ERROR_MEDIUM_INACCESSIBLE = 2020,
  E_ERROR_IDENTIFICATION_UNAVAILABLE = 2021,
  E_ERROR_INVALID_CHECKSUM = 2022,
  E_ERROR_ILLEGAL_OPERATION = 2023,
  E_ERROR_INFORMATION_NOT_ACCESSIBLE = 2024,
  E_ERROR_INFORMATION_NOT_PRESENT = 2025,
  E_ERROR_IDENTIFICATION_ALTERED = 2026,
  // range reserved upto 2099.

  // Dallas Dongles and other keys
  E_ERROR_COULD_NOT_FIND_THE_DALSEMI_KEYS = 2100,
  E_ERROR_DALSEMI_DRIVER_NOT_FOUND = 2101,
  E_ERROR_DALSEMI_KEYOPEN_FAILED = 2102,
  E_ERROR_DALSEMI_SETUP_FAILED = 2103,
  E_ERROR_DALSEMI_GNDTEST_FAILED = 2104,
  E_ERROR_DALSEMI_ACCESS_FAILED = 2105,
  E_ERROR_DALSEMI_NOT_A_TIME_BUTTON = 2107,
  E_ERROR_DALSEMI_BAD_BUTTON_TIME = 2108,
  E_ERROR_DALSEMI_WRITE_PROTECTED = 2109,
  E_ERROR_DALSEMI_NOT_A_MULTI_BUTTON = 2110,
  E_ERROR_TOO_MANY_KEYS = 2106,
  E_ERROR_DOMINO_DRIVER_NOT_FOUND = 2120,
  E_ERROR_DOMINO_ACCESS_FAILED = 2121,
  E_ERROR_DOMINO_UNKNOWN_BOARD = 2122,
  E_ERROR_PICOLO_DRIVER_NOT_FOUND = 2130,
  E_ERROR_PICOLO_ACCESS_FAILED = 2131,
  E_ERROR_PICOLO_UNKNOWN_BOARD = 2132,
  E_ERROR_MULTI_DRIVER_NOT_FOUND = 2133,
  E_ERROR_MULTI_ACCESS_FAILED = 2134,
  E_ERROR_MULTI_UNKNOWN_BOARD = 2135,
  E_ERROR_SENTINEL_INTERNAL_ERROR = 2136,
  E_ERROR_SENTINEL_DRIVER_NOT_FOUND = 2137,
  E_ERROR_SENTINEL_ACCESS_FAILED = 2138,
  E_ERROR_UNKNOWN_SENTINEL_DEVELOPER_ID = 2139,
  E_ERROR_CANNOT_READ_EURECARD_EXTERNAL_NUMBER = 2140,
  E_ERROR_SIRCAM_DRIVER_NOT_FOUND = 2141,
  E_ERROR_SIRCAM_ACCESS_FAILED = 2142,
  E_ERROR_SIRCAM_UNKNOWN_BOARD = 2143,

  // Warp
  E_ERROR_WARP_IMAGES_TOO_SMALL = 2200,

  // Scanner
  E_ERROR_SCANNER_ERROR = 2500,

  // EasyImage
  E_ERROR_UNSUPPORTED_IMAGE_SIZE = 2600,

  // EasyObject
  E_ERROR_UNABLE_TO_ACCESS_CODED_IMAGE_MEMORY = 3000,
  E_ERROR_FEATURE_DEPENDENCY_ERROR = 3001,
  E_ERROR_OBJECT_TOO_SMALL_FOR_FEATURE = 3002,
  E_ERROR_UNKNOWN_FEATURE = 3003,
  E_ERROR_INVALID_SELECTION_ARGUMENT = 3004,
  E_ERROR_SORT_LIST_TOO_LONG = 3005,
  E_ERROR_NOT_A_VALID_OPERATION_CODE = 3006,
  E_ERROR_TOO_MANY_OBJECTS_DETECTED = 3008,
  E_ERROR_TOO_MANY_RUNS_DETECTED = 3009,
  E_ERROR_TIME_OUT_REACHED = 3010,
  E_ERROR_TOO_MANY_RUNS = 3011,
  E_ERROR_INVALID_FEATURE = 3012,
  E_ERROR_FEATURE_NOT_CALCULATED = 3013,
  E_ERROR_BAD_OBJECT_NUMBER = 3014,
  E_ERROR_NO_OBJECT_SELECTED = 3015,
  E_ERROR_LOW_THRESHOLD_HIGHER_THAN_HIGH_THRESHOLD = 3016,
  E_ERROR_INVALID_THRESHOLD_MODE = 3017,

  // EasyMeasure
  E_ERROR_MEASURE_OBJ_MUST_NOT_BE_POINT = 4001,

  // EasyOPV
  E_ERROR_BROKEN_OBJECT = 5000,
  E_ERROR_SUPERFLUOUS_OBJECT = 5001,
  E_ERROR_MISSING_OBJECT = 5002,
  E_ERROR_OBJECT_UNDER_THRESHOLD = 5003,
  E_ERROR_OBJECT_OVER_THRESHOLD = 5004,

  // EasyMatch
  E_ERROR_NO_PATTERN_LEARNT = 6000,
  E_ERROR_PATTERN_TOO_LARGE = 6001,
  E_ERROR_PATTERN_TOO_SMALL = 6002,
  E_ERROR_UNSUPPORTED_SCALING_MODE = 6003,
  E_ERROR_NOT_AN_EASY_MATCH_FILE = 6004,
  E_ERROR_UNSUPPORTED_EASY_MATCH_FILE_VERSION = 6005,
  E_ERROR_NO_IMAGE_LEARNT = 6006,
  E_ERROR_WRONG_NUMBER_OF_DEGREES_OF_FREEDOM = 6007,

  // EasyFind
  E_ERROR_INSUFFICIENT_CONTRAST = 6500,
  E_ERROR_NOT_AN_EASY_FIND_FILE = 6501,
  E_ERROR_UNSUPPORTED_EASY_FIND_FILE_VERSION = 6502,
  E_ERROR_PATTERN_TOO_CLOSE_TO_IMAGE_BORDER = 6503,
  E_ERROR_PATTERN_NOT_LEARNT = 6504,
  E_ERROR_INCOMPATIBLE_MODES = 6505,
  E_ERROR_NO_UNIFORM_BACKGROUND = 6506,
  E_ERROR_ALLOWANCES_AND_PATTERNTYPE_NOT_COMPATIBLE = 6507,
  E_ERROR_UNABLE_TO_EXTRACT_REGION = 6508,

  // EasyOCR
  E_ERROR_NO_PATTERNS_LOADED = 7000,
  E_ERROR_NO_PATTERNS_IN_THESE_CLASSES = 7001,
  E_INFO_TOO_FEW_CHARACTERS_FOUND = 101,
  E_INFO_TOO_MANY_CHARACTERS_FOUND = 102,
  E_ERROR_CHARACTER_TOO_SMALL = 7004,

  // EasyHCR
  E_INFO_WORD_NOT_FOUND = 103,
  E_ERROR_NO_SUCH_NGRAM = 8001,
  E_ERROR_INDEX_FULL = 8002,
  E_ERROR_WORD_LIST_FULL = 8003,
  E_ERROR_INVALID_FIELD_TYPE = 8004,
  E_ERROR_NO_CLASSIFIER_FOR_TEXT_OR_NUMBER_FIELD = 8005,
  E_ERROR_INCOMPATIBLE_FIELD_TYPES = 8006,

  // EasyColor
  E_ERROR_MISMATCHING_COLOR_SYSTEM = 9000,
  E_ERROR_COLOR_LOOKUP_MUST_BE_INITIALIZED = 9001,
  E_ERROR_UNSUPPORTED_COLOR_TRANSFORM = 9002,

  // EasyMatrixCode
  /*  
  E_ERROR_INVALID_ASCII_CHARACTER = 10001,
  E_ERROR_INVALID_C40_CHARACTER = 10002,
  E_ERROR_INVALID_TEXT_CHARACTER = 10003,
  E_ERROR_INVALID_X12_CHARACTER = 10004,
  E_ERROR_INVALID_EDIFACT_CHARACTER = 10005,
  E_ERROR_INVALID_BASE256_CHARACTER = 10006,
  */
  E_INFO_INVALID_ASCII_PADDING = 107,
  E_ERROR_UNKNOWN_SYMBOL_SIZE = 10008,
  E_ERROR_UNKNOWN_ECC_FAMILY = 10009,
  E_ERROR_NOT_ENOUGH_CORNERS = 10010,
  E_ERROR_UNCORRECTABLE_ERRORS = 10011,
  E_ERROR_COULD_NOT_LOCATE_SYMBOL = 10012,
  E_ERROR_UNKNOWN_FORMAT_ID = 10013,
  E_ERROR_INVALID_CRC = 10014,
  E_ERROR_NOT_AN_EASY_MATRIX_CODE_FILE = 10015,
  E_ERROR_UNSUPPORTED_EASY_MATRIX_CODE_FILE_VERSION = 10016,
  E_ERROR_COULD_NOT_LOCATE_SYMBOL_AREA = 10017,
  E_ERROR_COULD_NOT_LOCATE_SYMBOL_SIZE = 10018,
  E_ERROR_COULD_NOT_LOCATE_SINGLE_SYMBOL = 10019,
  E_ERROR_COULD_NOT_DETERMINE_SYMBOL_SIZE = 10020,
  E_ERROR_COULD_NOT_DECODE_SYMBOL = 10021,

  // EasyBarCode
  E_ERROR_COULD_NOT_LOCATE_BARCODE = 10501,
  E_ERROR_COULD_NOT_LOCATE_SINGLE_BARCODE = 10502,
  E_ERROR_UNRECOGNIZED_SIGNATURE = 10503,
  E_ERROR_INVALID_NUMBER_OF_BARS = 10504,
  E_ERROR_EXTRA_EDGES_FOUND = 10505,
  E_ERROR_INCOHERENT_BAR_SPACE_THICKNESS = 10506,
  E_ERROR_INVALID_CHECK_CHARACTER = 10507,
  E_ERROR_SYMBOLOGY_NOT_ENABLED = 10508,
  E_ERROR_NO_EDGES_FOUND = 10509,

  // EasyOCV
  E_ERROR_NOT_AN_EASY_OCV_FILE = 11001,
  E_ERROR_UNSUPPORTED_EASY_OCV_FILE_VERSION = 11002,
  E_ERROR_NOT_ENOUGH_SAMPLE_IMAGES = 11003,
  E_ERROR_NOT_AN_ECHECKER_FILE = 11004,
  E_ERROR_UNSUPPORTED_ECHECKER_FILE_VERSION = 11005,
  E_ERROR_TEXT_LOCATION_OUT_OF_IMAGE = 11006,
  E_ERROR_NOT_ENOUGH_SAMPLES_LEARNT = 11007,
  E_ERROR_INVALID_NORMALIZATION_MODE = 11008,
  E_ERROR_IMAGE_NOT_REGISTERED = 11009,
  E_ERROR_INVALID_LEARNING_SEQUENCE = 11010,

  // EasyInspect
  E_ERROR_SHAPE_ALREADY_HAS_A_MOTHER = 12001,
  E_ERROR_MOTHER_ALREADY_HAS_THIS_DAUGHTER = 12002,
  E_ERROR_MOTHER_ALREADY_HAS_DAUGHTERS = 12003,
  E_ERROR_SHAPE_ALREADY_HAS_THIS_DAUGHTER = 12004,
  E_ERROR_SHAPE_ALREADY_HAS_DAUGHTERS = 12005,

  E_ERROR_SINGULAR_TRANSFORM = 12006,
  E_ERROR_NO_VALID_POINT_FOUND = 12007,
  E_ERROR_NOT_IN_LIST_ATTACHMENT_MODE = 12008,
  E_ERROR_NOT_IN_INDEXED_ATTACHMENT_MODE = 12009,

  E_ERROR_UNSUPPORTED_SHAPE_VERSION = 12010,

  E_ERROR_RAW_CALIBRATION_MODE = 12011,
  E_ERROR_USER_CALIBRATION_MODE = 12012,
  E_ERROR_INCOMPATIBLE_CALIBRATION_MODES = 12013,
  E_ERROR_NOT_ENOUGH_LANDMARKS = 12014,

  E_ERROR_UNEXPECTED_SHAPE_TYPE_IN_FILE = 12015,
  E_ERROR_UNSUPPORTED_MODEL_FILE_VERSION = 12016,

  E_ERROR_CANNOT_ATTACH_DETACH_WORLD_SHAPES = 12017,

  E_ERROR_UNEXPECTED_WORLD_SHAPE_IN_FILE = 12018,
  E_ERROR_UNEXPECTED_FRAME_SHAPE_IN_FILE = 12019,
  E_ERROR_UNEXPECTED_POINT_SHAPE_IN_FILE = 12020,
  E_ERROR_UNEXPECTED_LINE_SHAPE_IN_FILE = 12021,
  E_ERROR_UNEXPECTED_CIRCLE_SHAPE_IN_FILE = 12022,
  E_ERROR_UNEXPECTED_RECTANGLE_SHAPE_IN_FILE = 12023,
  E_ERROR_UNEXPECTED_WEDGE_SHAPE_IN_FILE = 12024,
  E_ERROR_UNEXPECTED_POINT_GAUGE_IN_FILE = 12025,
  E_ERROR_UNEXPECTED_LINE_GAUGE_IN_FILE = 12026,
  E_ERROR_UNEXPECTED_CIRCLE_GAUGE_IN_FILE = 12027,
  E_ERROR_UNEXPECTED_RECTANGLE_GAUGE_IN_FILE = 12028,
  E_ERROR_UNEXPECTED_WEGDE_GAUGE_IN_FILE = 12029,
  E_ERROR_UNEXPECTED_FIND_IN_FILE = 12030,
  E_ERROR_UNEXPECTED_BAR_CODE_IN_FILE = 12031,
  E_ERROR_UNEXPECTED_BGA_IN_FILE = 12032,
  E_ERROR_UNEXPECTED_BGA_COMPONENT_IN_FILE = 12033,
  E_ERROR_UNEXPECTED_BGA_ARRAY_IN_FILE = 12034,
  E_ERROR_UNEXPECTED_BGA_BALL_IN_FILE = 12035,

  // EasyGauge
  E_ERROR_AN_ACTIVE_CURVED_EDGE_IS_REQUIRED = 12100,

  //WedgeGauge
  E_ERROR_BROKEN_WEDGE_SHAPE_CONSTRAINTS = 12200,
  

  // EasyBGA
  E_ERROR_NO_COMPONENT = 13001,
  E_ERROR_NO_SUCH_COMPONENT = 13002,
  E_ERROR_CANNOT_EDIT_MULTIPLE_COMPONENTS = 13003,
  E_ERROR_NO_ARRAY = 13004,
  E_ERROR_NO_SUCH_ARRAY = 13005,
  E_ERROR_NO_BALL = 13006,
  E_ERROR_NO_SUCH_BALL = 13007,
  E_ERROR_WORLD_CALIBRATION_FAILED = 13008,
  E_ERROR_BALLS_CALIBRATION_FAILED = 13009,
  E_ERROR_INVALID_MEASURE_ASSESSMENT_FLAGS = 13010,
  E_ERROR_INVALID_CIRCULARITY_ASSESSMENT_FLAGS = 13011,

  // EasyMultiCam
  E_ERROR_CANNOT_LINK_CHANNEL_TO_BOARD = 14001,
  E_ERROR_CANNOT_LINK_PROCESSOR_TO_BOARD = 14002,
  E_ERROR_NO_BOARD_CORRESPONDING_TO_BOARDNAME = 14003,
  E_ERROR_NO_BOARD_CORRESPONDING_TO_BOARDIDENTIFIER = 14004,
  E_ERROR_NO_BOARD_CORRESPONDING_TO_DRIVERINDEX = 14005,
  E_ERROR_NO_BOARD_CORRESPONDING_TO_PCIPOSITION = 14006,
  E_ERROR_MODEL_LOAD_FAILED = 14007,
  E_ERROR_CAM_FILE_LOAD_FAILED = 14008,
  E_ERROR_CANNOT_FIND_FREE_PROCESSOR = 14009,
  E_ERROR_CHANNEL_CREATION_FAILED_WHEN_OTHER_ACTIVE = 14011,
  E_ERROR_CANNOT_ACTIVATE_THE_CHANNEL = 14012,
  E_ERROR_CANNOT_DESACTIVATE_THE_CHANNEL = 14013,
  E_ERROR_NULL_EMCCHANNEL_POINTER = 14014,
  E_ERROR_NULL_EMCCONFIGURATION_POINTER = 14015,
  E_ERROR_EMCOPEN_FAILURE = 14016,
  E_ERROR_CANNOT_APPLY_TO_AN_EMCIMAGE = 14017,
  E_ERROR_NOT_IMPLEMENTED = 14018,
  E_ERROR_OPEN_FAILURE = E_ERROR_EMCOPEN_FAILURE,
  E_ERROR_REGISTER_CONFIGURATION_SIGNAL_CALLBACK_FAILURE = 14019, 
  E_ERROR_REGISTER_CONFIGURATION_ERROR_CALLBACK_FAILURE = 14020, 
  E_ERROR_INVALID_MODEL = 14021, 
  E_ERROR_INVALID_STANDARD = 14026, 
  E_ERROR_UNSUPPORTED_FUNCTION = 14027, 
  E_ERROR_INCONSISTENT_MODEL_FOR_SPECIFIED_BOARD = 14028,
  E_ERROR_EMCIMAGE_NOT_ASSIGNED = 14029,
  E_ERROR_CHANNEL_CREATION_WIZARD_FAILURE = 14030,
  E_ERROR_IMAGE_TYPE_DIFFERS_FROM_SOURCE = 14031,

  E_ERROR_MULTICAM_0 = 14100,
  E_ERROR_MULTICAM_NO_BOARD_FOUND = 14101,
  E_ERROR_MULTICAM_BAD_PARAMETER = 14102,
  E_ERROR_MULTICAM_IO_ERROR = 14103,
  E_ERROR_MULTICAM_INTERNAL_ERROR = 14104,
  E_ERROR_MULTICAM_NO_MORE_RESOURCES = 14105,
  E_ERROR_MULTICAM_IN_USE = 14106,
  E_ERROR_MULTICAM_NOT_SUPPORTED = 14107,
  E_ERROR_MULTICAM_DATABASE_ERROR = 14108,
  E_ERROR_MULTICAM_OUT_OF_BOUND = 14109,
  E_ERROR_MULTICAM_INSTANCE_NOT_FOUND = 14110,
  E_ERROR_MULTICAM_INVALID_HANDLE = 14111,
  E_ERROR_MULTICAM_TIMEOUT = 14112,
  E_ERROR_MULTICAM_INVALID_VALUE = 14113,
  E_ERROR_MULTICAM_RANGE_ERROR = 14114,
  E_ERROR_MULTICAM_BAD_HW_CONFIG = 14115,
  E_ERROR_MULTICAM_NO_EVENT = 14116,
  E_ERROR_MULTICAM_LICENSE_NOT_GRANTED = 14117,
  E_ERROR_MULTICAM_FATAL_ERROR = 14118,
  E_ERROR_MULTICAM_HW_EVENT_CONFLICT = 14119,
  E_ERROR_MULTICAM_FILE_NOT_FOUND = 14120,

  E_ERROR_MULTICAM_PICOLO_0 = 14200,
  E_ERROR_MULTICAM_PICOLO_DEVICE_NOT_FOUND = 14201,
  E_ERROR_MULTICAM_PICOLO_INVALID_PARAMETER = 14202,
  E_ERROR_MULTICAM_PICOLO_TIMEOUT = 14203,
  E_ERROR_MULTICAM_PICOLO_INVALID_HANDLE = 14204,
  E_ERROR_MULTICAM_PICOLO_SURFACE_ERROR = 14205,
  E_ERROR_MULTICAM_PICOLO_CHANNEL_ERROR = 14206,
  E_ERROR_MULTICAM_PICOLO_SYSTEM_ERROR = 14207,
  E_ERROR_MULTICAM_PICOLO_UNSUCCESSFUL = 14208,
  E_ERROR_MULTICAM_PICOLO_NO_DATA = 14209,
  E_ERROR_MULTICAM_PICOLO_INVALID_PARAMETER_VALUE = 14210,
  E_ERROR_MULTICAM_PICOLO_NOT_IMPLEMENTED = 14300,

  // Jpeg Library
  E_ERROR_IJPEG_BASE_ERROR                  = 15000,
  E_ERROR_IJPEG_EXCEPTION_DETECTED          = 15000+1,
  E_ERROR_IJPEG_INVALID_ENCODER             = 15000+2,
  E_ERROR_IJPEG_UNSUPPORTED_SUBSAMPLING     = 15000+3,
  E_ERROR_IJPEG_UNSUPPORTED_BYTES_PER_PIXEL = 15000+4,
  E_ERROR_IJPEG_MEMORY_ERROR                = 15000+5,
  E_ERROR_IJPEG_BAD_HUFFMAN_TABLE           = 15000+6,
  E_ERROR_IJPEG_BAD_QUANT_TABLE             = 15000+7,
  E_ERROR_IJPEG_INVALID_JPEG_PROPERTIES     = 15000+8,
  E_ERROR_IJPEG_ERR_FILECLOSE               = 15000+9,
  E_ERROR_IJPEG_INVALID_FILENAME            = 15000+10,
  E_ERROR_IJPEG_ERROR_EOF                   = 15000+11,
  E_ERROR_IJPEG_PROG_NOT_SUPPORTED          = 15000+12,
  E_ERROR_IJPEG_ERR_NOT_JPEG                = 15000+13,
  E_ERROR_IJPEG_ERR_COMP                    = 15000+14,
  E_ERROR_IJPEG_ERR_SOF                     = 15000+15,
  E_ERROR_IJPEG_ERR_DNL                     = 15000+16,
  E_ERROR_IJPEG_ERR_NO_HUF                  = 15000+17,
  E_ERROR_IJPEG_ERR_NO_QUAN                 = 15000+18,
  E_ERROR_IJPEG_ERR_NO_FRAME                = 15000+19,
  E_ERROR_IJPEG_ERR_MULT_FRAME              = 15000+20,
  E_ERROR_IJPEG_ERR_DATA                    = 15000+21,
  E_ERROR_IJPEG_ERR_NO_IMAGE                = 15000+22,
  E_ERROR_IJPEG_FILE_ERROR                  = 15000+23,
  E_ERROR_IJPEG_INTERNAL_ERROR              = 15000+24,
  E_ERROR_IJPEG_BAD_RST_MARKER              = 15000+25,
  E_ERROR_IJPEG_THUMBNAIL_DIB_TOO_SMALL     = 15000+26,
  E_ERROR_IJPEG_THUMBNAIL_DIB_WRONG_COLOR   = 15000+27,
  E_ERROR_IJPEG_BUFFER_TOO_SMALL            = 15000+28,
  E_ERROR_IJPEG_UNSUPPORTED_FRAME           = 15000+29,
  E_ERROR_IJPEG_ERR_COM_BUFFER              = 15000+30,
  E_ERROR_IJPEG_RESERVED                    = 15000+99,
  E_ERROR_IJPEG_UNKNOWN                     = 15000+100,
  E_ERROR_IJPEG_SOI_MARKER_NOT_FOUND        = 15000+101,
  E_ERROR_IJPEG_EOI_MARKER_NOT_FOUND        = 15000+102,
  E_ERROR_IJPEG_CORRUPTED_JPEG_BUFFER       = 15000+103,
  E_ERROR_IJPEG_EMPTY_JPEG_BUFFER           = 15000+104,
  E_ERROR_IJPEG_LAST_ERROR                  = 15000+105,

  E_ERROR_UNKNOWN  = 0xFFFFFFFF
};


// Angular modes
enum E_ANGLE_UNITS
{
  E_ANGLE_UNIT_REVOLUTIONS,
  E_ANGLE_UNIT_RADIANS,
  E_ANGLE_UNIT_DEGREES,
  E_ANGLE_UNIT_GRADES,
  E_ANGLE_UNIT_UNKWOWN  = 0xFFFFFFFF
};


// Trace modes
enum E_TRACE_MODE
{
  E_TRACE_DISPLAY_MESSAGE = 0,
  E_TRACE_SILENT = 1,
  E_TRACE_DISPLAY_FULL_MESSAGE = 2,

  E_TRACE_SILENT_ETRACE = E_TRACE_SILENT | E_ETRACE_USED,
  E_TRACE_DISPLAY_MESSAGE_ETRACE = E_TRACE_DISPLAY_MESSAGE | E_ETRACE_USED,
  E_TRACE_DISPLAY_FULL_MESSAGE_ETRACE = E_TRACE_DISPLAY_FULL_MESSAGE | E_ETRACE_USED,

  E_TRACE_UNKNOWN  = 0xFFFFFFFF
};

// Selected items processing mode
enum E_SELECTION_MODE
{ 
  E_SELECTED_ANY,
  E_SELECTED_TRUE,
  E_SELECTED_FALSE,
  E_SELECTED_UNKNOWN  = 0xFFFFFFFF
};


// Pixel data types
enum DATA_TYPE
{ 
  E_DATA_TYPE_UNSIGNED_INT = 1,
  E_DATA_TYPE_SIGNED_INT = 2, 
  E_DATA_TYPE_FLOAT = 4,
  E_DATA_TYPE_UNKNOWN  = 0xFFFFFFFF
};


// Predefined vector types
enum VECT_TYPE
{ 
  E_VECT_TYPE_CONTOUR = 1, 
  E_VECT_TYPE_HIST = 2, 
  E_VECT_TYPE_LUT_UINT8 = 3,
  E_VECT_TYPE_SEG = 4, 
  E_VECT_TYPE_PEAK = 5,
  E_VECT_TYPE_MEASURE = 6,
  E_VECT_TYPE_LUT_FLOAT32 = 7,
  E_VECT_TYPE_UNKNOWN  = 0xFFFFFFFF
};

// Data size
enum DATA_SIZE
{
  E_1_BIT_DATA = 1, 
  E_8_BIT_DATA = 2,
  E_16_BIT_DATA = 4, 
  E_32_BIT_DATA = 8, 
  E_64_BIT_DATA = 16,
  E_24_BIT_DATA = 32,
  E_96_BIT_DATA = 64,
  E_24_BITS_PER_PIXEL = E_24_BIT_DATA,
  E_1_BIT_PER_PIXEL = E_1_BIT_DATA, 
  E_8_BITS_PER_PIXEL = E_8_BIT_DATA,
  E_16_BITS_PER_PIXEL = E_16_BIT_DATA, 
  E_32_BITS_PER_PIXEL = E_32_BIT_DATA, 
  E_64_BITS_PER_PIXEL = E_64_BIT_DATA,
  E_96_BITS_PER_PIXEL = E_96_BIT_DATA,
  E_SIZE_DATA_UNKNOWN  = 0xFFFFFFFF
};


enum E_RGB_STANDARD
{
  E_RGB_STANDARD_NTSC,
  E_RGB_STANDARD_PAL,
  E_RGB_STANDARD_SMPTE, // UNUSED
  E_RGB_STANDARD_UNKNOWN  = 0xFFFFFFFF
};

enum E_COLOR_QUANTIZATION
{
  E_COLOR_QUANTIZATION_FULL_RANGE,
  E_COLOR_QUANTIZATION_CCIR_601,
  E_COLOR_QUANTIZATION_UNKNOWN  = 0xFFFFFFFF
};

// + OBSOLETE
enum VECTOR_USE
{
  E_VECT_USE_NONE, 
  E_VECT_USE_HIST, 
  E_VECT_USE_CONTOUR,
  E_VECT_USE_MEASU,
  E_VECT_USE_PROJ, 
  E_VECT_USE_SEG, 
  E_VECT_USE_EXTREM,
  E_VECT_USE_TRANS, 
  E_VECT_USE_COMPARE,
  E_VECT_USE_PEAK,
  E_VECT_USE_LUT,
  E_VECT_USE_UNKNOWN  = 0xFFFFFFFF
};
// - OBSOLETE


// Predefined measurement units
enum E_MEASUREMENT_UNITS
{ 
  E_UNIT_NONE,
  E_UNIT_UM, 
  E_UNIT_MM,
  E_UNIT_CM,
  E_UNIT_DM,
  E_UNIT_M,
  E_UNIT_DAM,
  E_UNIT_HM,
  E_UNIT_KM,
  E_UNIT_MIL, 
  E_UNIT_INCH, 
  E_UNIT_FOOT, 
  E_UNIT_YARD, 
  E_UNIT_MILE,
  E_UNIT_UNKNOWN  = 0xFFFFFFFF
};


enum E_EVISION_LICENSES
{
  E_EVISION_LICENSE_EASY,
  E_EVISION_LICENSE_EASYIMAGE,
  E_EVISION_LICENSE_EASYCOLOR,
  E_EVISION_LICENSE_EASYOBJECT,
  E_EVISION_LICENSE_EASYMEASURE,
  E_EVISION_LICENSE_EASYOCR,
  E_EVISION_LICENSE_EASYOCV,
  E_EVISION_LICENSE_EASYMATCH,
  E_EVISION_LICENSE_EASYMATRIXCODE,
  E_EVISION_LICENSE_EASYINSPECT,
  E_EVISION_LICENSE_EASYBGA,
  E_EVISION_LICENSE_EASYFIND,
  E_EVISION_LICENSE_EASYGAUGE,
  E_EVISION_LICENSE_EASYBARCODE,
  E_EVISION_LICENSE_SPECIAL1,
  E_EVISION_LICENSE_UNKNOWN = 0xFFFFFFFF
};


enum E_EJPEGHANDLER_SCALINGMODE
{
  E_EJPEGHANDLER_FULL,
  E_EJPEGHANDLER_HALF,
  E_EJPEGHANDLER_QUARTER,
  E_EJPEGHANDLER_EIGHTH
};


#endif
