// EBarCode_Enum.h: EasyBarCode library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __EMBARCODE_ENUM_H__
#define __EMBARCODE_ENUM_H__


enum BRC_SYMBOLOGIES
{
  BRC_STANDARD_SYMBOLOGY = 0x1,
  BRC_ADDITIONAL_SYMBOLOGY = 0x2,

  // Standard types
  BRC_CODABAR = 0x4 | BRC_STANDARD_SYMBOLOGY,
  BRC_CODE_128 = 0x8 | BRC_STANDARD_SYMBOLOGY,
  BRC_CODE_25_INTERLEAVED = 0x10 | BRC_STANDARD_SYMBOLOGY,
  BRC_CODE_39 = 0x20 | BRC_STANDARD_SYMBOLOGY,
  BRC_EAN_128 = 0x40 | BRC_STANDARD_SYMBOLOGY,
  BRC_EAN_13 = 0x80 | BRC_STANDARD_SYMBOLOGY,  
  BRC_MSI = 0x100 | BRC_STANDARD_SYMBOLOGY,
  BRC_UPC_A = 0x200 | BRC_STANDARD_SYMBOLOGY,            
  BRC_UPC_E = 0x400 | BRC_STANDARD_SYMBOLOGY,

  // Keep up-to-date
  BRC_FIRST_STANDARD = BRC_CODABAR,
  BRC_LAST_STANDARD = BRC_UPC_E,

  // Additional types 
  BRC_BINARY_CODE = 0x4 | BRC_ADDITIONAL_SYMBOLOGY,
  BRC_ADS_ANKER = 0x8 | BRC_ADDITIONAL_SYMBOLOGY,
  BRC_BC_412 = 0x10 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_CODE_11 = 0x20 | BRC_ADDITIONAL_SYMBOLOGY,
  BRC_CODE_13 = 0x40 | BRC_ADDITIONAL_SYMBOLOGY,
  BRC_CODE_25_DATALOGIC = 0x80 | BRC_ADDITIONAL_SYMBOLOGY,  
  BRC_CODE_25_MATRIX = 0x100 | BRC_ADDITIONAL_SYMBOLOGY,    
  BRC_CODE_25_IATA = 0x200 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_CODE_25_INDUSTRY = 0x400 | BRC_ADDITIONAL_SYMBOLOGY,    
  BRC_CODE_25_COMPRESSED = 0x800 | BRC_ADDITIONAL_SYMBOLOGY,
  BRC_CODE_25_INVERTED = 0x1000 | BRC_ADDITIONAL_SYMBOLOGY,    
  BRC_CODE_32 = 0x2000 | BRC_ADDITIONAL_SYMBOLOGY,              
  BRC_CODE_39_EXTENDED = 0x4000 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_CODE_39_REDUCED = 0x8000 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_CODE_93 = 0x10000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_CODE_93_EXTENDED = 0x20000 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_CODE_BCD_MATRIX = 0x40000 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_CODE_CIP = 0x80000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_CODE_STK = 0x100000 | BRC_ADDITIONAL_SYMBOLOGY,            
  BRC_EAN_8 = 0x200000 | BRC_ADDITIONAL_SYMBOLOGY,            
  BRC_IBM_DELTA_DISTANCE_A = 0x400000 | BRC_ADDITIONAL_SYMBOLOGY,      
  BRC_PLESSEY = 0x800000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_TELEPEN = 0x1000000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_RSS_14 = 0x2000000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_RSS_14_LIMITED = 0x4000000 | BRC_ADDITIONAL_SYMBOLOGY,          
  BRC_RSS_14_EXPANDED = 0x8000000 | BRC_ADDITIONAL_SYMBOLOGY,          

  // Keep up-to-date
  BRC_FIRST_ADDITIONAL = BRC_BINARY_CODE,
  BRC_LAST_ADDITIONAL = BRC_RSS_14_EXPANDED,

  // Groups
  BRC_STANDARD = BRC_CODABAR | BRC_CODE_128 | BRC_CODE_25_INTERLEAVED | BRC_CODE_39 |
  BRC_EAN_128 | BRC_EAN_13 | BRC_MSI | BRC_UPC_A | BRC_UPC_E,

  BRC_ADDITIONAL = BRC_BINARY_CODE | BRC_ADS_ANKER | BRC_BC_412 | BRC_CODE_11 |
  BRC_CODE_25_DATALOGIC | BRC_CODE_25_MATRIX | BRC_CODE_25_IATA | BRC_CODE_25_INDUSTRY | 
  BRC_CODE_25_COMPRESSED | BRC_CODE_25_INVERTED | BRC_CODE_32 | BRC_CODE_39_EXTENDED | 
  BRC_CODE_39_REDUCED | BRC_CODE_93 | BRC_CODE_93_EXTENDED | BRC_CODE_BCD_MATRIX | BRC_CODE_CIP |
  BRC_CODE_STK | BRC_EAN_8 | BRC_IBM_DELTA_DISTANCE_A | BRC_PLESSEY | BRC_TELEPEN | BRC_CODE_13 |
  BRC_RSS_14 | BRC_RSS_14_LIMITED | BRC_RSS_14_EXPANDED,

  BRC_SYMBOLOGY_UNKNOWN  = 0xFFFFFFFF
};


enum BRC_SYMBOL_DIRECTIONS
{
  // Orientation
  BRC_LEFT_TO_RIGHT = 0x1,
  BRC_RIGHT_TO_LEFT = 0x2,

  BRC_HORIZONTAL = BRC_LEFT_TO_RIGHT | BRC_RIGHT_TO_LEFT,

  BRC_BOTTOM_TO_TOP = 0x4,
  BRC_TOP_TO_BOTTOM = 0x8,

  BRC_VERTICAL = BRC_BOTTOM_TO_TOP | BRC_TOP_TO_BOTTOM,

  BRC_FOUR_WAYS = BRC_HORIZONTAL | BRC_VERTICAL,

  BRC_OBLIQUE = 0x10,

  BRC_DIRECTION_UNKNOWN  = 0xFFFFFFFF,
};


#endif //__EMBARCODE_ENUM_H__
