// EBGA_Enum.h: EasyBGA library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __EBGA_ENUM_H__
#define __EBGA_ENUM_H__

enum BGA_DIAGNOSTICS
{
  BGA_DIAGNOSTIC_CLUTTER = 0x1,
  BGA_DIAGNOSTIC_MISSING_BALL = 0x2,
  BGA_DIAGNOSTIC_BAD_BALL_OFFSET = 0x4,
  BGA_DIAGNOSTIC_BAD_BALL_PITCH = 0x8,
  BGA_DIAGNOSTIC_BAD_BALL_DIAMETER = 0x10,
  BGA_DIAGNOSTIC_BAD_BALL_SHAPE = 0x20,
  BGA_DIAGNOSTIC_BAD_BALL_COLOR = 0x40,
  BGA_DIAGNOSTIC_BAD_BALL_QUALITY = 0x80,
  BGA_DIAGNOSTIC_EXTRA_BALL = 0x100,

  BGA_DIAGNOSTIC_UNKNOWN  = 0xFFFFFFFF
};


enum BGA_MEASURE_BALL
{
  BGA_MEASURE_BALL_OK,
  BGA_MEASURE_BALL_FAILURE,
  BGA_MEASURE_BALL_OUT_OF_IMAGE,
  BGA_MEASURE_BALL_TOO_LARGE,
  BGA_MEASURE_BALL_NO_EDGE,
  BGA_MEASURE_BALL_NOT_A_DOUGHNUT,

  BGA_MEASURE_BALL_UNKNOWN  = 0xFFFFFFFF
};


enum BGA_SYMMETRY
{
  BGA_SYMMETRY_NONE,
  BGA_SYMMETRY_2H,
  BGA_SYMMETRY_2V,
  BGA_SYMMETRY_4,
  BGA_SYMMETRY_8,

  BGA_SYMMETRY_UNKNOWN  = 0xFFFFFFFF
};

enum BGA_QUALITY_INDICATORS
{
  BGA_DIAMETER_QUALITY = 0x1,
  BGA_CIRCULARITY_QUALITY = 0x2,
  BGA_PITCH_QUALITY = 0x4,
  BGA_OFFSET_QUALITY = 0x8,
  BGA_DOUGHNUTNESS_QUALITY = 0x10,
  BGA_GRAY_LEVEL_QUALITY = 0x20,   // corresponds to 'Quality Factor' parameter.

  BGA_ALL_QUALITIES = BGA_DIAMETER_QUALITY | BGA_CIRCULARITY_QUALITY | BGA_PITCH_QUALITY | BGA_OFFSET_QUALITY | BGA_DOUGHNUTNESS_QUALITY | BGA_GRAY_LEVEL_QUALITY,

  BGA_PER_BATCH_QUALITY = 0x100,

  BGA_QUALITY_UNKNOWN  = 0xFFFFFFFF
};

enum BGA_MEASURE_ASSESSMENT
{
  BGA_BASIC_MEASURE_ASSESSMENT = 0x1,
  BGA_FINE_MEASURE_ASSESSMENT,
  BGA_ROBUST_MEASURE_ASSESSMENT,

  BGA_UNKNOWN_MEASURE_ASSESSMENT = 0xFFFFFFFF
};

enum BGA_CIRCULARITY_ASSESSMENT
{
  BGA_BASIC_CIRCULARITY_ASSESSMENT = 0x1,
  BGA_FINE_CIRCULARITY_ASSESSMENT,

  BGA_UNKNOWN_CIRCULARITY_ASSESSMENT = 0xFFFFFFFF
};



#endif //__EBGA_ENUM_H__
