// EFind_Enum.h: EasyFind library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __FIND_ENUM_H__
#define __FIND_ENUM_H__


enum FND_PATTERN_TYPE
{
  FND_CONSISTENT_EDGES,
  FND_UNIFORM_BACKGROUND,
  FND_UNKNOWN = 0xFFFFFFFF
};

enum FND_CONTRAST_MODE
{
  FND_CONTRAST_NORMAL,
  FND_CONTRAST_INVERSE,
  FND_CONTRAST_ANY,
  FND_CONTRAST_UNKNOWN = 0xFFFFFFFF
};

enum FND_FEATURE_SELECTION
{
  FND_ALL,
  FND_STRONGEST,
  FND_STRONGEST_MAXIMA,
  FND_STRONGEST_XY_MAXIMA,
  FND_SAMPLED,
  FND_SAMPLED_MAXIMA,
  FND_SAMPLED_XY_MAXIMA,
  FND_CANNY,

  FND_SYNTHETIC = FND_STRONGEST,
  FND_NATURAL = FND_CANNY,
  FND_HOMOGENEOUS = FND_ALL,

  FND_FEATURE_SELECTION_UNKNOWN = 0xFFFFFFFF
};


enum FND_LOCAL_SEARCH_MODE
{
  FND_LOCAL_SEARCH_BASIC,
  FND_LOCAL_SEARCH_EXTENDED_TRANSLATION,
  FND_LOCAL_SEARCH_EXTENDED_ALL,
  FND_LOCAL_SEARCH_EXTENDED_MORE,

  FND_LOCAL_SEARCH_UNKNOWN = 0xFFFFFFFF
};



enum FND_COARSE_TO_FINE_ANALYSIS_MODE
{
  // Public modes
  FND_COARSE_TO_FINE_ANALYSIS_MODE_KEEP_BLACK_LINES,
  FND_COARSE_TO_FINE_ANALYSIS_MODE_KEEP_WHITE_LINES,
  FND_COARSE_TO_FINE_ANALYSIS_MODE_UNIFORM,

  FND_COARSE_TO_FINE_ANALYSIS_MODE_UNKNOWN = 0xFFFFFFFF
};


#endif //__FIND_ENUM_H__
