// EMatch_Enum.h: EasyMatch library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __EMATCH_ENUM_H__
#define __EMATCH_ENUM_H__


#define MCH_MAX_REDUCTIONS 8

// + OBSOLETE
#define E_MATCH_STANDARD          E_STANDARD
#define E_MATCH_OFFSET_NORMALIZED E_OFFSET_NORMALIZED
#define E_MATCH_GAIN_NORMALIZED   E_GAIN_NORMALIZED
#define E_MATCH_NORMALIZED        E_NORMALIZED
// - OBSOLETE

enum E_CORRELATION_MODE
{ 
  E_MATCH_STANDARD,
  E_MATCH_OFFSET_NORMALIZED,
  E_MATCH_GAIN_NORMALIZED, 
  E_MATCH_NORMALIZED,
  E_MATCH_CONTRASTED,
  E_MATCH_CORRELATION_MODE_UNKNOWN = 0xFFFFFFFF
};


enum MCH_CONTRAST_MODE
{
  MCH_CONTRAST_NORMAL,
  MCH_CONTRAST_INVERSE,
  MCH_CONTRAST_ANY,
  MCH_CONTRAST_UNKNOWN = 0xFFFFFFFF
};


enum MCH_FILTERING_MODE
{
  MCH_UNIFORM,
  MCH_LOWPASS,
  MCH_EDGE,
  MCH_FILTERING_UNKNOWN = 0xFFFFFFFF
};

enum MCH_REDUCTION_DECAY_MODE
{
  MCH_GEOMETRIC_DECAY,
  MCH_FAST_GEOMETRIC_DECAY,
  MCH_REDUCTION_DECAY_UNKNOW = 0xFFFFFFFF
};


#endif //__EMATCH_ENUM_H__
