// EObject_Enum.h: EasyObject library header file for eVision 6.7.1.0
//
// Copyright ( c) 1997-2006, Euresys. All rights reserved.
//

#ifndef __EOBJECT_ENUM_H__
#define __EOBJECT_ENUM_H__


////////////////////////////////////////////////////////////////////////////////
// Enumeration constants

// Contour connexity
enum OBJECT_CONNEXITY
{
  OBJ_CONNEXITY_4, 
  OBJ_CONNEXITY_8,
  OBJ_CONNEXITY_UNKNOWN  = 0xFFFFFFFF
};


enum RUN_TYPE
{ 
  OBJ_CODE_RUN_WHITE = 1, 
  OBJ_CODE_RUN_NEUTRAL = 2, 
  OBJ_CODE_RUN_BLACK = 4,
  OBJ_CODE_RUN_UNKNOWN  = 0xFFFFFFFF
};

enum SELECT_OPTIONS
{ 
  OBJ_INSERT_ALL, 
  OBJ_INSERT_GREATER_OR_EQUAL, 
  OBJ_INSERT_LESSER_OR_EQUAL, 
  OBJ_INSERT_RANGE, 
  OBJ_REMOVE_ALL, 
  OBJ_REMOVE_GREATER_OR_EQUAL, 
  OBJ_REMOVE_LESSER_OR_EQUAL, 
  OBJ_REMOVE_RANGE,
  OBJ_INSERT_OUT_OF_RANGE, 
  OBJ_REMOVE_OUT_OF_RANGE,
  OBJ_SELECT_OPTIONS_UNKNOWN  = 0xFFFFFFFF
};

enum SELECT_BY_POSITION
{ 
  OBJ_INSERT_IN, 
  OBJ_INSERT_TOUCH, 
  OBJ_INSERT_OUT, 
  OBJ_REMOVE_IN, 
  OBJ_REMOVE_TOUCH, 
  OBJ_REMOVE_OUT, 
  OBJ_REMOVE_BORDER,
  OBJ_SELECT_BY_POSITION_UNKNOWN  = 0xFFFFFFFF
};

enum SORT_OPTIONS
{ 
  OBJ_SORT_ASCENDING, 
  OBJ_SORT_DESCENDING,
  OBJ_SORT_UNKNOWN  = 0xFFFFFFFF
};

enum OBJECT_FEATURES
{ 
  OBJ_NONE = 0,
  OBJ_CLASS = 1, 
  OBJ_RUNS_NUMBER = 2, 
  OBJ_AREA = 3, 
  OBJ_LARGEST_RUN = 4, 
  OBJ_GRAVITY_CENTER_X = 5, 
  OBJ_GRAVITY_CENTER_Y = 6, 
  OBJ_LIMIT_CENTER_X = 7, 
  OBJ_LIMIT_CENTER_Y = 8, 
  OBJ_LIMIT_WIDTH = 9, 
  OBJ_LIMIT_HEIGHT = 10, 
  OBJ_LIMIT45_CENTER_X = 11, 
  OBJ_LIMIT45_CENTER_Y = 12, 
  OBJ_LIMIT45_WIDTH = 13, 
  OBJ_LIMIT45_HEIGHT = 14, 
  OBJ_CONTOUR_X = 15, 
  OBJ_CONTOUR_Y = 16, 
  OBJ_PIXEL_MIN = 17, 
  OBJ_PIXEL_MAX = 18, 
  OBJ_SIGMA_X = 19, 
  OBJ_SIGMA_Y = 20, 
  OBJ_SIGMA_XY = 21, 
  OBJ_SIGMA_XX = 22, 
  OBJ_SIGMA_YY = 23, 
  OBJ_ELLIPSE_WIDTH = 24, 
  OBJ_ELLIPSE_HEIGHT = 25, 
  OBJ_ELLIPSE_ANGLE = 26, 
  OBJ_CENTROID_X = 27, 
  OBJ_CENTROID_Y = 28, 
  OBJ_PIXEL_GRAY_AVERAGE = 29,
  OBJ_PIXEL_GRAY_VARIANCE = 30,
  OBJ_LIMIT22_CENTER_X = 31, 
  OBJ_LIMIT22_CENTER_Y = 32, 
  OBJ_LIMIT22_WIDTH = 33, 
  OBJ_LIMIT22_HEIGHT = 34, 
  OBJ_LIMIT68_CENTER_X = 35, 
  OBJ_LIMIT68_CENTER_Y = 36, 
  OBJ_LIMIT68_WIDTH = 37, 
  OBJ_LIMIT68_HEIGHT = 38, 
  OBJ_LIMIT_ANGLED_CENTER_X = 39, 
  OBJ_LIMIT_ANGLED_CENTER_Y = 40, 
  OBJ_LIMIT_ANGLED_WIDTH = 41, 
  OBJ_LIMIT_ANGLED_HEIGHT = 42,
  OBJ_FERET_CENTER_X = 43,
  OBJ_FERET_CENTER_Y = 44,
  OBJ_FERET_WIDTH = 45,
  OBJ_FERET_HEIGHT = 46,
  OBJ_FERET_ANGLE = 47,
  OBJ_OBJ_NUM = 48, 

  OBJ_GRAVITY_CENTER = OBJ_GRAVITY_CENTER_X, 
  OBJ_LIMIT = OBJ_LIMIT_CENTER_X,
  OBJ_LIMIT22 = OBJ_LIMIT22_CENTER_X,
  OBJ_LIMIT45 = OBJ_LIMIT45_CENTER_X,
  OBJ_LIMIT68 = OBJ_LIMIT68_CENTER_X,
  OBJ_LIMIT_ANGLED = OBJ_LIMIT_ANGLED_CENTER_X,
  OBJ_ELLIPSE = OBJ_ELLIPSE_WIDTH, 
  OBJ_CENTROID = OBJ_CENTROID_X,
  OBJ_FERET = OBJ_FERET_CENTER_X,

  OBJ_FEATURES_UNKNOWN  = 0xFFFFFFFF
};

// Thresholding modes
enum OBJ_THRESHOLD_MODES
{
  OBJ_SIMPLE_THRESHOLD,
  OBJ_DOUBLE_THRESHOLD,
  OBJ_COLOR_THRESHOLD,

  OBJ_THRESHOLD_UNKNOWN  = 0xFFFFFFFF
};




#endif //__EOBJECT_ENUM_H__
